cluster_name: "${CLUSTER_NAME}"

ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false

kubernetes_version: ""

ignore_docker_version: null
enable_cri_dockerd: null

private_registries: []

bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
  ignore_proxy_env_vars: false

services:
  etcd:
    image: ""
  kube-api:
    image: ""
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
  kubelet:
    image: ""
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""

authentication:
  strategy: x509
  sans: []
  webhook: null

authorization:
  mode: rbac
  options: {}

network:
  plugin: ${NETWORK_PLUGIN}
  options: {}
  mtu: 0
  node_selector: {}
  update_strategy: null
  tolerations: []

dns: null

monitoring:
  provider: ""
  options: {}
  node_selector: {}
  update_strategy: null
  replicas: null
  tolerations: []
  metrics_server_priority_class_name: ""

ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
  update_strategy: null
  http_port: 0
  https_port: 0
  network_mode: ""
  tolerations: []
  default_backend: null
  default_http_backend_priority_class_name: ""
  nginx_ingress_controller_priority_class_name: ""
  default_ingress_class: null

addons: ""
addons_include: []

cloud_provider:
  name: ""

prefix_path: ""
win_prefix_path: ""
addon_job_timeout: 0

restore:
  restore: false
  snapshot_name: ""

rotate_encryption_key: false

