# -*- mode: ruby -*-
# vi: set ft=ruby :

ssh_script = <<EOS
ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
EOS

Vagrant.configure("2") do |config|
  #config.vm.box = "generic/centos7"
  config.vm.box = "bento/almalinux-8"
  config.ssh.insert_key = false

  config.vm.define "bastion" do |c|
    # Mount current dir to home directory
    c.vm.synced_folder "../../", "/home/vagrant/rke-support", "owner": "vagrant", "group": "vagrant"

    c.vm.hostname = "bastion"
    c.vm.network "private_network", ip: "192.168.56.10"
    #c.vm.network "forwarded_port", guest: 22, host: 2310, id: "ssh"
    c.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  (0..2).each do |n|
    config.vm.define "node-#{n}" do |c|
      c.vm.hostname = "node-#{n}"
      c.vm.network "private_network", ip: "192.168.56.2#{n}"
      #c.vm.network "forwarded_port", guest: 22, host: 2320 + n, id: "ssh"
      c.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
      end
    end
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled  = true
    config.proxy.http     = "#{ENV['http_proxy']}"
    config.proxy.https    = "#{ENV['https_proxy']}"
    config.proxy.no_proxy = "#{ENV['no_proxy']},192.168.56.0/24"
  end
end
