- name: Check /etc/selinux/config exists
  stat:
    path: /etc/selinux/config
  register: selinux_config

- name: Disable SELinux
  selinux:
    state: disabled
  when: selinux_config.stat.exists == true
