- name: Uninstall docker.io if present
  apt:
    name: docker-io
    state: absent
  become: yes

- name: Add apt_key of docker apt repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  #environment: "{{ proxy_env }}"
  become: yes

#- name: Get lsb_release
#  shell: lsb_release -cs
#  ignore_errors: True
#  register: lsb_release

- name: Add docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    #repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    filename: docker
    state: present
  become: yes
