- include_tasks: "{{ ansible_os_family }}.yml"

- name: Install / update docker-ce
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Create /etc/docker directory
  become: yes
  file:
    path: /etc/docker
    state: directory

- name: Install daemon.json for insecure registries
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart_docker

- when: http_proxy != ""
  become: yes
  block:
    - name: Create /etc/systemd/system/docker.service.d
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Install http-proxy.conf for docker
      template:
        src: http-proxy.conf.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      notify: restart_docker

- name: Enable /start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Get current user
  command: whoami
  register: whoami

- name: Add {{ whoami.stdout }} to docker group
  become: yes
  user:
    name: "{{ whoami.stdout }}"
    groups: docker
    append: yes
